%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Composability
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{compositionalityarticle}[2018/05/27, v0.1]

\LoadClass{extarticle}

\RequirePackage[T1]{fontenc}
\RequirePackage{merriweather}

\RequirePackage{amsmath,amsfonts,amssymb}

\RequirePackage{authblk}

\newcommand{\leadauthor}[1]{\def\@leadauthor{#1}}
\newcommand{\keywords}[1]{\def\@keywords{#1}}

%\RequirePackage{xcolor}

%\definecolor{mutedcoral}{RGB}{255,90,95}
%\definecolor{palecoral}{RGB}{255,166,158}
%\definecolor{darkgrey}{RGB}{51,51,51}
%\definecolor{lightgrey}{RGB}{170,170,170}

% fonts.google.com/selection?query=merriweather&selection.famlity=Merriweather:400,400i,700|Raleway:400,400,700



